-- =====================================================================
-- Nudo Hub — notification_prefs table & server-side push preference gate
-- =====================================================================
-- Preferred shape: Dedicated table `notification_prefs`.
-- Why table over jsonb on profiles:
--   1. Extensibility: Additive per category (new categories like 'caja',
--      'auditoria' require zero schema changes or migrations).
--   2. Granular RLS: Updating a single category preference never races with
--      or overwrites profile row edits (e.g. branch, role, phone updates).
--   3. Query Performance: Enables clean, indexed SQL JOINs when server
--      functions query push_subscriptions for dispatch.
--
-- Default: All categories are ON by default. A missing row and an explicit
-- true behave identically. Absence of a row = enabled.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.notification_prefs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    category text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT notification_prefs_user_category_key UNIQUE (user_id, category)
);

-- Fast lookup index for recipient preference evaluation
CREATE INDEX IF NOT EXISTS idx_notification_prefs_user_cat
    ON public.notification_prefs (user_id, category);

-- Enable Row Level Security
ALTER TABLE public.notification_prefs ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------
-- RLS POLICIES
-- A user reads and writes ONLY their own rows.
-- Management (Dueño / Gerente Regional) may read all for support.
-- ---------------------------------------------------------------------

DROP POLICY IF EXISTS notification_prefs_select ON public.notification_prefs;
CREATE POLICY notification_prefs_select ON public.notification_prefs
    FOR SELECT
    USING (
        auth.uid() = user_id
        OR EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid()
              AND profiles.role IN ('Dueño', 'Gerente Regional')
        )
    );

DROP POLICY IF EXISTS notification_prefs_insert ON public.notification_prefs;
CREATE POLICY notification_prefs_insert ON public.notification_prefs
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS notification_prefs_update ON public.notification_prefs;
CREATE POLICY notification_prefs_update ON public.notification_prefs
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS notification_prefs_delete ON public.notification_prefs;
CREATE POLICY notification_prefs_delete ON public.notification_prefs
    FOR DELETE
    USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------
-- SERVER-SIDE ENFORCEMENT FUNCTIONS
-- Used by Edge Functions, RPCs, background jobs, and PostgreSQL triggers.
-- If a lookup fails, it logs via RAISE WARNING and DOES NOT silently drop.
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.is_push_enabled_for_user(p_user_id uuid, p_category text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_enabled boolean;
BEGIN
    IF p_user_id IS NULL OR p_category IS NULL THEN
        RETURN true;
    END IF;

    SELECT enabled INTO v_enabled
    FROM public.notification_prefs
    WHERE user_id = p_user_id AND category = p_category;
    
    -- Default is ON: missing row (null) or true means enabled.
    RETURN COALESCE(v_enabled, true);
EXCEPTION WHEN OTHERS THEN
    -- A failed lookup logs and does NOT silently drop
    RAISE WARNING 'Preference lookup failed for user %, category %: %', p_user_id, p_category, SQLERRM;
    RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_push_subscriptions_for_category(p_category text, p_user_ids uuid[] DEFAULT NULL)
RETURNS SETOF public.push_subscriptions
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT ps.*
    FROM public.push_subscriptions ps
    LEFT JOIN public.notification_prefs np
      ON np.user_id = ps.user_id AND np.category = p_category
    WHERE (p_user_ids IS NULL OR ps.user_id = ANY(p_user_ids))
      AND COALESCE(np.enabled, true) = true;
EXCEPTION WHEN OTHERS THEN
    -- A failed lookup logs and does NOT silently drop
    RAISE WARNING 'Category push subscription filter failed for category %: %', p_category, SQLERRM;
    RETURN QUERY
    SELECT ps.*
    FROM public.push_subscriptions ps
    WHERE (p_user_ids IS NULL OR ps.user_id = ANY(p_user_ids));
END;
$$;
